-- =========================================================================
-- 1. TABLAS MAESTRAS (Catálogos)
-- =========================================================================

CREATE SCHEMA DBO;

CREATE TABLE DBO.FACULTAD (
    COD_FACULTAD INT NOT NULL PRIMARY KEY,
    SIGLAS VARCHAR(10),
    NOMBRE_FACULTAD VARCHAR(100)
);

CREATE TABLE DBO.CARRERA (
    COD_CARRERA INT NOT NULL PRIMARY KEY,
    NOMBRE_CARRERA VARCHAR(150),
    COD_FACULTAD VARCHAR(150)
);

CREATE TABLE DBO.TIPO_CREDITO (
    COD_TIPO_CREDITO INT NOT NULL PRIMARY KEY,
    NOMBRE_TIPO_CREDITO VARCHAR(50)
);

CREATE TABLE DBO.TIPO_REQUISITO (
    COD_TIPO_REQUISITO VARCHAR(10) NOT NULL PRIMARY KEY,
    NOMBRE_TIPO_REQUISITO VARCHAR(50)
);

CREATE TABLE DBO.MATERIA (
    COD_MATERIA INT NOT NULL PRIMARY KEY,
    NOMBRE_MATERIA VARCHAR(100),
    CODIGO_MATERIA VARCHAR(50)
);

CREATE TABLE DBO.ESTUDIANTE (
    COD_ESTUDIANTE BIGINT NOT NULL,
    COD_CARRERA INT,
    ANIO INT NOT NULL,
    TERMINO VARCHAR(100) NOT NULL,
    PRIMARY KEY (COD_ESTUDIANTE, ANIO, TERMINO)
);

CREATE TABLE DBO.GRADUADOS (
    COD_CARRERA INT NOT NULL,
    ANIO INT NOT NULL,
    CANTIDAD_GRADUADOS INT,
    PRIMARY KEY (COD_CARRERA, ANIO)
);

CREATE TABLE DBO.INGRESOS (
    COD_CARRERA INT NOT NULL,
    ANIO INT NOT NULL,
    TERMINO VARCHAR(255) NOT NULL,
    TOTAL_INGRESO_ADM INT,
    TOTAL_INGRESO_CAMBIO INT,
    PRIMARY KEY (COD_CARRERA, ANIO, TERMINO)
);

CREATE TABLE DBO.PERIODO (
    ANIO INT NOT NULL,
    TERMINO VARCHAR(100) NOT NULL,
    NOMBRE_PERIODO VARCHAR(100),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    FECHA_INICIO_CLASES DATE,
    FECHA_FIN_CLASES DATE,
    FECHA_INICIO_PLAN DATE,
    FECHA_FIN_PLAN DATE,
    PRIMARY KEY (ANIO, TERMINO)
);

CREATE TABLE DBO.USUARIO (
    NOMBRE_USUARIO VARCHAR(50) NOT NULL PRIMARY KEY,
    PASSWORD VARCHAR(50),
    COD_CARRERA INT
);

-- =========================================================================
-- 2. TABLAS PUENTE (Relaciones N a M)
-- =========================================================================

CREATE TABLE DBO.MATERIA_CARRERA (
    COD_CARRERA INT NOT NULL,
    COD_MATERIA INT NOT NULL,
    NIVEL_CARRERA VARCHAR(100),
    COD_TIPO_CREDITO INT,
    PRIMARY KEY (COD_CARRERA, COD_MATERIA)
);

CREATE TABLE DBO.REQUISITOS (
    COD_MATERIA INT NOT NULL,
    COD_MATERIA_REQUISITO INT NOT NULL,
    COD_TIPO_REQUISITO VARCHAR(10) NOT NULL,
    PRIMARY KEY (COD_MATERIA, COD_MATERIA_REQUISITO, COD_TIPO_REQUISITO)
);

-- =========================================================================
-- 3. TABLAS TRANSACCIONALES (Hechos)
-- =========================================================================

CREATE TABLE DBO.PLANIFICACION (
    COD_CURSO INT NOT NULL,
    ANIO INT,
    TERMINO INT,
    COD_MATERIA INT,
    COD_PARALELO INT,
    CUPO_PLANIFICADO INT,
    PARALELO_CANCELADO VARCHAR(1),
    APROBADO VARCHAR(1),
    INSCRITOS INT
);

CREATE TABLE DBO.INSCRIPCIONES (
    COD_INSCRIPCION INT NOT NULL PRIMARY KEY,
    ANIO INT,
    TERMINO VARCHAR(255),
    COD_PARALELO INT,
    COD_CURSO INT,
    COD_MATERIA INT,
    COD_ESTUDIANTE BIGINT,
    COD_ESTADO_CURSO VARCHAR(5),
    PROMEDIO DECIMAL(5,2)
);

