-- DBO.VW_METRICAS_CARRERA_ANIO source

CREATE OR REPLACE VIEW DBO.VW_METRICAS_CARRERA_ANIO AS
WITH CTE AS (
SELECT
    i.ANIO ,
    COALESCE(e.COD_CARRERA, 999) COD_CARRERA,
    COALESCE(c.NOMBRE_CARRERA, 'OTROS') NOMBRE_CARRERA,
    count (DISTINCT i.COD_ESTUDIANTE ) AS CANTIDAD_ESTUDIANTES,
    count (i.COD_ESTUDIANTE) AS CANTIDAD_INSCRIPCIONES,
    sum(CASE WHEN i.cod_estado_curso = 'AP' THEN 1 ELSE 0 END) AS CANTIDAD_APROBADOS,
    sum(CASE WHEN i.cod_estado_curso = 'RP' THEN 1 ELSE 0 END) AS CANTIDAD_REPROBADOS
FROM
    DBO.INSCRIPCIONES i
LEFT JOIN DBO.ESTUDIANTE e ON
    i.COD_ESTUDIANTE = e.COD_ESTUDIANTE
    AND i.ANIO = e.ANIO
    AND i.TERMINO = e.TERMINO
LEFT JOIN DBO.CARRERA c ON
    e.cod_carrera = c.COD_CARRERA
GROUP BY
    i.ANIO,
    e.COD_CARRERA,
    c.NOMBRE_CARRERA
)SELECT
    C.*,
    COALESCE( G.CANTIDAD_GRADUADOS, 0) AS cantidad_graduados,
    COALESCE(I.TOTAL_INGRESO_ADM, 0) TOTAL_INGRESO_ADM,
    COALESCE(I.TOTAL_INGRESO_CAMBIO, 0) TOTAL_INGRESO_CAMBIO
FROM
    CTE C
LEFT JOIN DBO.GRADUADOS G ON
    C.ANIO = G.ANIO
    AND C.COD_CARRERA = G.COD_CARRERA
LEFT JOIN (
    SELECT
        ANIO,
        COD_CARRERA,
        SUM(TOTAL_INGRESO_ADM) AS TOTAL_INGRESO_ADM,
        SUM(TOTAL_INGRESO_CAMBIO) AS TOTAL_INGRESO_CAMBIO
    FROM
        DBO.INGRESOS
    GROUP BY
        ANIO,
        COD_CARRERA)
			I ON
    C.ANIO = I.ANIO
    AND C.COD_CARRERA = I.COD_CARRERA;

-- DBO.VW_METRICAS_CARRERA_PERIODO source

CREATE OR REPLACE VIEW DBO.VW_METRICAS_CARRERA_PERIODO AS
WITH CTE AS (
SELECT
    p.NOMBRE_PERIODO,
    i.ANIO ,
    i.TERMINO,
    COALESCE(e.COD_CARRERA, 999) AS COD_CARRERA,
    COALESCE(c.NOMBRE_CARRERA, 'OTROS') AS NOMBRE_CARRERA,
    count(DISTINCT i.COD_ESTUDIANTE ) AS CANTIDAD_ESTUDIANTES,
    count(i.COD_ESTUDIANTE) AS CANTIDAD_INSCRIPCIONES,
    sum(CASE WHEN i.cod_estado_curso = 'AP' THEN 1 ELSE 0 END) AS CANTIDAD_APROBADOS,
    sum(CASE WHEN i.cod_estado_curso = 'RP' THEN 1 ELSE 0 END) AS CANTIDAD_REPROBADOS
FROM
    DBO.INSCRIPCIONES i
LEFT JOIN DBO.ESTUDIANTE e ON
    i.COD_ESTUDIANTE = e.COD_ESTUDIANTE
    AND i.ANIO = e.ANIO
    AND i.TERMINO = e.TERMINO
LEFT JOIN DBO.CARRERA c ON
    e.cod_carrera = c.COD_CARRERA
LEFT JOIN DBO.PERIODO p ON
    i.ANIO = P.ANIO
    AND I.TERMINO = P.TERMINO
GROUP BY
    p.NOMBRE_PERIODO,
    i.ANIO ,
    i.TERMINO,
    e.COD_CARRERA,
    c.NOMBRE_CARRERA
)SELECT
    C.*,
    COALESCE(I.TOTAL_INGRESO_ADM, 0) TOTAL_INGRESO_ADM,
    COALESCE(I.TOTAL_INGRESO_CAMBIO, 0) TOTAL_INGRESO_CAMBIO
FROM
    CTE C
LEFT JOIN DBO.INGRESOS I ON
    C.ANIO = I.ANIO
    AND C.COD_CARRERA = I.COD_CARRERA
    AND i.termino = c.termino;


-- DBO.VW_METRICAS_MATERIA source

CREATE OR REPLACE VIEW DBO.VW_METRICAS_MATERIA AS 
WITH CTE AS (
SELECT
    p.NOMBRE_PERIODO,
    i.ANIO ,
    i.TERMINO,
    COALESCE(e.COD_CARRERA, 999) COD_CARRERA,
    COALESCE(c.NOMBRE_CARRERA, 'OTROS') NOMBRE_CARRERA,
    I.COD_MATERIA,
    COALESCE(M.NOMBRE_MATERIA, 'N/A') AS NOMBRE_MATERIA,
    COALESCE(m.CODIGO_MATERIA, 'N/A') AS CODIGO_MATERIA,
    count(DISTINCT i.COD_ESTUDIANTE ) AS CANTIDAD_ESTUDIANTES,
    count(i.COD_ESTUDIANTE) AS CANTIDAD_INSCRIPCIONES,
    count(CASE WHEN i.cod_estado_curso = 'AP' THEN i.cod_estudiante ELSE NULL END) AS CANTIDAD_APROBADOS,
    count(CASE WHEN i.cod_estado_curso = 'RP' THEN i.cod_estudiante ELSE NULL END) AS CANTIDAD_REPROBADOS,
    CAST(COALESCE(ROUND(AVG(i.PROMEDIO), 2), 0.00) AS decimal(18, 2)) AS PROMEDIO_MATERIA
FROM
    DBO.INSCRIPCIONES i
LEFT JOIN DBO.ESTUDIANTE e ON
    i.COD_ESTUDIANTE = e.COD_ESTUDIANTE
    AND i.ANIO = e.ANIO
    AND i.TERMINO = e.TERMINO
LEFT JOIN DBO.CARRERA c ON
    e.cod_carrera = c.COD_CARRERA
LEFT JOIN DBO.PERIODO p ON
    i.ANIO = P.ANIO
    AND I.TERMINO = P.TERMINO
LEFT JOIN DBO.MATERIA m ON
    i.COD_MATERIA = M.COD_MATERIA
GROUP BY
    p.NOMBRE_PERIODO,
    i.ANIO ,
    i.TERMINO,
    e.COD_CARRERA,
    c.NOMBRE_CARRERA,
    I.COD_MATERIA,
    M.NOMBRE_MATERIA,
    M.CODIGO_MATERIA
)SELECT
    C.*,
    COALESCE( mc.NIVEL_CARRERA, 'N/A') NIVEL_CARRERA ,
    COALESCE(mc.COD_TIPO_CREDITO, 5) AS COD_TIPO_CREDITO
FROM
    CTE C
LEFT JOIN DBO.MATERIA_CARRERA mc ON
    c.COD_MATERIA = Mc.COD_MATERIA
    AND c.cod_carrera = mc.COD_CARRERA;
